/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigDrawer: typeof import('./components/ConfigDrawer/ConfigDrawer.vue')['default']
    Drawer: typeof import('./components/ConfigDrawer/Drawer.vue')['default']
    DSPElDialog: typeof import('./components/DSPElDialog/DSPElDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnReadme: typeof import('./components/EnReadme.md')['default']
    FormulaSelectionDialog: typeof import('./components/FormulaSelectionDialog/FormulaSelectionDialog.vue')['default']
    'IAntDesign:deleteFilled': typeof import('~icons/ant-design/delete-filled')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    'IZondicons:arrowThickDown': typeof import('~icons/zondicons/arrow-thick-down')['default']
    'IZondicons:arrowThickUp': typeof import('~icons/zondicons/arrow-thick-up')['default']
    'IZondicons:arrowThinRight': typeof import('~icons/zondicons/arrow-thin-right')['default']
    'IZondicons:exclamationOutline': typeof import('~icons/zondicons/exclamation-outline')['default']
    'IZondicons:indentDecrease': typeof import('~icons/zondicons/indent-decrease')['default']
    'IZondicons:indentIncrease': typeof import('~icons/zondicons/indent-increase')['default']
    Left: typeof import('./components/Left.vue')['default']
    ProductImg: typeof import('./components/ProductImg.vue')['default']
    Right: typeof import('./components/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFactory: typeof import('./components/SelectFactory/SelectFactory.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
