name: static-page
on:
  push:
    branches: [add-gh-pages]

env:
  VITE_API_BASEURL: "/api"
  VITE_BASE: "./"
  VITE_APP_TITLE: "戴森球计划量化计算器"
  VITE_APP_DESCRIPTION: "A zero-config Vue3 template includes Vite3、Vue3 and TypeScript"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install --force
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
